[versions]
paper = "1.21.4-R0.1-SNAPSHOT"
hikari = "6.2.1"
slf4j = "2.0.16"
junit = "5.11.4"
mockito = "5.15.2"
shadow = "9.0.0-beta4"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }